
CREATE DATABASE Homework; #создание базы данных Homework

CREATE TABLE Students (
    StudentID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    DateOfBirth DATE
);

CREATE TABLE Courses (
    CourseID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CourseName VARCHAR(100),
    Description TEXT,
    Credits INT
);

CREATE TABLE Enrollments (
    EnrollmentID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EnrollmentDate DATE
);

CREATE TABLE Assignments (
    AssignmentID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AssignmentName VARCHAR(100),
    DueDate DATE
);

INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES
('John', 'Doe', '2000-01-15'),
('Jane', 'Smith', '1999-02-20'),
('Emily', 'Jones', '2001-03-30');

INSERT INTO Courses (CourseName, Description, Credits) VALUES
('Mathematics', 'An introductory course to Mathematics', 3),
('History', 'World history from ancient to modern times', 4),
('Computer Science', 'Basics of programming and algorithms', 3);

INSERT INTO Enrollments (EnrollmentDate) VALUES
('2023-01-15'),
('2023-01-15'),
('2023-01-16'),
('2023-01-17');

INSERT INTO Assignments (AssignmentName, DueDate) VALUES
('Homework 1', '2023-02-01'),
('Homework 2', '2023-03-01'),
('Essay 1', '2023-02-15'),
('Project 1', '2023-02-20');